trigger:
  branches:
    include:
    - main

resources:
  repositories:
    - repository: templates
      type: git
      name: Plumbing/core-templates
    - repository: eslint-config.js
      type: git
      name: Open/eslint-config.js

stages:
- template: stages/sync/sync.yml@templates  # Template reference
  parameters:
    checkout: eslint-config.js
